# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    clientId: '%env(CLIENT_ID)%'
    clientSecret: '%env(CLIENT_SECRET)%'
    urlAuthorize: '%env(ENDPOINT_ROOT)%/trustedx-authserver/oauth/izenpe'
    urlAccessToken: '%env(ENDPOINT_ROOT)%/trustedx-authserver/oauth/izenpe/token'
    urlResourceOwnerDetails: '%env(ENDPOINT_ROOT)%/trustedx-resources/openid/v1/users/me'
    redirectUri: 'app_giltza'
    maxFileSize: '%env(MAX_FILE_SIZE)%'
    minFileSize: '%env(MIN_FILE_SIZE)%'
    uploadDir: '%env(UPLOAD_DIR)%'
    downloadUri: '%env(DOWNLOAD_URI)%'
    mailerFrom: '%env(MAILER_FROM)%'
    mailerBCC: '%env(MAILER_BCC)%'
    receiverDomain: '%env(RECEIVER_DOMAIN)%'
    sendMessagesReceiver: '%env(bool:SEND_MESSAGES_TO_RECEIVER)%'
    sendMessagesSender: '%env(bool:SEND_MESSAGES_TO_SENDER)%'
    sendBCC: '%env(bool:SEND_BCC)%'
    receptionEmail: '%env(RECEPTION_EMAIL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $clientId: '%clientId%'
            $clientSecret: '%clientSecret%'
            $urlAuthorize: '%urlAuthorize%'
            $urlAccessToken: '%urlAccessToken%'
            $urlResourceOwnerDetails: '%urlResourceOwnerDetails%'
            $redirectUri: '%redirectUri%'
            $maxFileSize: '%maxFileSize%'
            $minFileSize: '%minFileSize%'
            $uploadDir: '%uploadDir%'
            $downloadUri: '%downloadUri%'
            $mailerFrom: '%mailerFrom%'
            $mailerBCC: '%mailerBCC%'
            $receiverDomain: '%receiverDomain%'
            $sendMessagesReceiver: '%sendMessagesReceiver%'
            $sendMessagesSender: '%sendMessagesSender%'
            $sendBCC: '%sendBCC%'
            $receptionEmail: '%receptionEmail%'


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
